name: Git Pull via SSH

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_USER: your-remote-username
  REMOTE_HOST: your-remote-hostname
  REMOTE_PATH: /path/to/repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa $REMOTE_HOST >> ~/.ssh/known_hosts

      - name: Git Pull via SSH
        run: ssh $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH && git pull"
